# services:
#   server:
#     build:
#       context: ./server
#     environment:
#       PORT: ${SERVER_PORT}
#       MONGODB_URI: ${MONGODB_URI}
#     ports:
#       - "${SERVER_PORT}:${SERVER_PORT}"

#   client:
#     build:
#       context: ./client
#       args:
#         VITE_API_URL: ${VITE_API_URL}
#     depends_on:
#       - server
#     ports:
#       - "${CLIENT_PORT}:${CLIENT_PORT}"

services:
  server:
    build:
      context: ./server
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: /api
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "80:80"
